# -*- coding: utf-8 -*-
"""Movie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyz0VXbjswhPYk0gS_ICXtil59TDCTAF
"""

import numpy as np
import pandas as pd

import ast

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

"""# Understanding Data"""

movies.head()

movies.shape

movies.isnull().sum()

credits.head()

credits.shape

"""# Merging Both the DataSets"""

movies = movies.merge(credits, on='title')

movies = movies[['movie_id',
                 'title',
                 'overview',
                 'genres',
                 'keywords',
                 'cast',
                 'crew']]

movies.dropna(inplace = True)

movies.head()

movies.shape

movies.isnull().sum()

movies.dropna(inplace = True)

"""# Data Preprocessing"""

def convert(obj):
    L = []

    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

def convert3(obj):
    L = []
    counter = 0

    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break

    return L

def fetch_director(obj):
    L = []

    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break

    return L

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)
movies['cast'] = movies['cast'].apply(convert3)
movies['crew'] = movies['crew'].apply(fetch_director)

movies['overview'] = movies['overview'].apply(lambda x:x.split())

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies['tags'] = movies['overview'] + 3*movies['genres'] + 2*movies['keywords'] + 1*movies['cast'] + 2*movies['crew']

new_df = movies[['movie_id','title','tags']]

new_df.head()

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

"""# **Stemming**"""

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

new_df.head()

new_df.shape

"""# **TF - IDF**"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1, 2),   # captures phrases like "science fiction"
    min_df=2,
    max_df=0.9
)

vectors = tfidf.fit_transform(new_df['tags'])

vectors.shape

"""Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

tf_idf_sim = cosine_similarity(vectors)

tf_idf_sim.shape

sorted(list(enumerate(tf_idf_sim[0])),
       reverse=True,
       key=lambda x:x[1])

def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = tf_idf_sim[movie_index]

    movies_list = sorted(list(enumerate(distances)),
                         reverse=True,
                         key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

recommend('Avatar')

"""# **Count Vectorizer**"""

#Vectorization

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors.shape

"""Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

cv_similarity = cosine_similarity(vectors)

new_df[new_df['title'] == 'Avatar'].index[0]

list(enumerate(cv_similarity[0]))

sorted(list(enumerate(cv_similarity[0])),
       reverse=True,
       key=lambda x:x[1])

def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = cv_similarity[movie_index]

    movies_list = sorted(list(enumerate(distances)),
                         reverse=True,
                         key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

recommend('Avatar')

"""# **Sentence Transformer**"""

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
#-----------------------------
# 1. Load embedding model
# -----------------------------
model = SentenceTransformer('all-MiniLM-L6-v2')

# -----------------------------
# 2. Generate embeddings
# -----------------------------
embeddings = model.encode(new_df['tags'].tolist(), show_progress_bar=True)

# -----------------------------
# 3. Cosine similarity matrix
# -----------------------------
similarity = cosine_similarity(embeddings)

# -----------------------------
# 4. Index mapping
# -----------------------------
indices = pd.Series(new_df.index, index=new_df['title']).drop_duplicates()

# -----------------------------
# 5. Recommendation function
# -----------------------------
def recommend(movie_title, top_n=5):
    idx = indices[movie_title]

    sim_scores = list(enumerate(similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:top_n+1]

    return [new_df.iloc[i[0]]['title'] for i in sim_scores]

# -----------------------------
# 6. Example
# -----------------------------
print(recommend("Avatar"))

final_sim = (
    0.1 * cv_similarity +
    0.3 * tf_idf_sim +
    0.6 * similarity
)

def recommend(movie):
    idx = new_df[new_df['title'] == movie].index[0]

    scores = list(enumerate(final_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    for i in scores:
        print(new_df.iloc[i[0]].title)

recommend("Titanic")

import pickle

pickle.dump(new_df, open('movies.pkl','wb'))

pickle.dump(final_sim, open('similarity.pkl','wb'))

API_KEY = "7f6deb75aa1f753c6aa8cb4e44ff1fa4"

import requests

movie_id = 19995

url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US"

response = requests.get(url)

data = response.json()

data

def fetch_poster(movie_id):

    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US"

    data = requests.get(url)

    data = data.json()

    poster_path = data.get('poster_path')

    if poster_path:
        full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    else:
        # Return a placeholder image if poster_path is not available
        full_path = "https://via.placeholder.com/500x750?text=No+Poster+Available"

    return full_path

fetch_poster(19995)

def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]

    recommended_movies = []
    recommended_posters = []

    for i in movies_list:

        movie_id = new_df.iloc[i[0]].movie_id

        recommended_movies.append(new_df.iloc[i[0]].title)

        recommended_posters.append(fetch_poster(movie_id))

    return recommended_movies, recommended_posters

movies, posters = recommend('Avatar')

movies

from IPython.display import Image, display

for poster in posters:
    display(Image(url=poster))

def fetch_reviews(movie_id):

    url = f"https://api.themoviedb.org/3/movie/{movie_id}/reviews?api_key={API_KEY}&language=en-US"

    data = requests.get(url)

    data = data.json()

    reviews = []

    for review in data.get('results', []):
        reviews.append(review['content'])

    return reviews

reviews = fetch_reviews(19995)

len(reviews)
if reviews:
    print(reviews[0])
else:
    print("No reviews available for this movie.")

# !pip install transformers
# !pip install torch

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

classifier("This movie was absolutely amazing")

def sentiment_score(reviews):

    if len(reviews) == 0:
        return 0

    scores = []

    for review in reviews:

        result = classifier(review[:512])[0]

        if result['label'] == 'POSITIVE':
            scores.append(result['score'])

        else:
            scores.append(1 - result['score'])

    return sum(scores) / len(scores)

reviews = fetch_reviews(19995)

score = sentiment_score(reviews)

score

def hybrid_recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:11]

    final_movies = []

    for i in movies_list:

        idx = i[0]

        similarity_score = i[1]

        movie_id = new_df.iloc[idx].movie_id

        title = new_df.iloc[idx].title

        poster = fetch_poster(movie_id)

        reviews = fetch_reviews(movie_id)

        sentiment = sentiment_score(reviews)

        final_score = (0.8 * similarity_score) + (0.2 * sentiment)

        final_movies.append({
            'title': title,
            'poster': poster,
            'similarity': similarity_score,
            'sentiment': sentiment,
            'final_score': final_score
        })

    final_movies = sorted(
        final_movies,
        reverse=True,
        key=lambda x:x['final_score']
    )

    return final_movies[:5]

results = hybrid_recommend('Atonement')

for movie in results:

    print(movie['title'])

    print("Similarity:", movie['similarity'])

    print("Sentiment:", movie['sentiment'])

    print("Final Score:", movie['final_score'])

    print()